# <font color="purple"><h3 align="center">Pandas Concatenate Tutorial</h3></font>

## <font color='blue'>Basic Concatenation</font>

In [1]:
import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [2]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [3]:
df = pd.concat([pakistani_weather, us_weather])
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

## <font color='blue'>Ignore Index</font>

In [4]:
df = pd.concat([pakistani_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

## <font color='blue'>Concatenation And Keys</font>

In [5]:
df = pd.concat([pakistani_weather, us_weather], keys=["pakistan", "us"])
df

                city  temperature  humidity
pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
us       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [6]:
df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [7]:
df.loc["pakistan"]

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

## <font color='blue'>Concatenation Using Index</font>

In [9]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[1,2,3])
temperature_df

       city  temperature
1   karachi           32
2    lahore           45
3  peshawar           30

In [10]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

      city  windspeed
1   lahore          7
0  karachi         12

In [14]:
df = pd.concat([temperature_df,windspeed_df],axis=1)
df

       city  temperature     city  windspeed
1   karachi         32.0   lahore        7.0
2    lahore         45.0      NaN        NaN
3  peshawar         30.0      NaN        NaN
0       NaN          NaN  karachi       12.0

## <font color='blue'>Concatenate dataframe with series</font>

In [15]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [18]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
1   karachi         32.0    Dry
2    lahore         45.0   Rain
3  peshawar         30.0    NaN
0       NaN          NaN  Humid